query APISurface(
  $block: Long!
  $hash: Bytes32!
  $txHash: Bytes32!
  $address: Address!
  $sender: Address!
  $slot: Bytes32!
  $topic: Bytes64!
  $index: Long!
) {
  block(number: $block) {
    number
    hash
    parent {
      number
      hash
    }
    transactionsRoot
    transactionCount
    stateRoot
    receiptsRoot
    miner(block: $block) {
      address
      balance
      transactionCount
      code
      storage(slot: $slot)
    }
    extraData
    gasLimit
    gasUsed
    baseFeePerGas
    nextBaseFeePerGas
    timestamp
    logsBloom
    random
    transactions {
      hash
      nonce
      index
      from {
        address
      }
      to {
        address
      }
      value
      maxFeePerGas
      maxPriorityFeePerGas
      effectiveTip
      gas
      inputData
      block {
        number
        hash
      }
      status
      gasUsed
      cumulativeGasUsed
      effectiveGasPrice
      createdContract {
        address
      }
      logs {
        index
        account {
          address
        }
        topics
        data
        transaction {
          hash
        }
      }
      descriptor
      extraParams
      signature
      publicKey
      type
      accessList {
        address
        storageKeys
      }
      raw
      rawReceipt
    }
    transactionAt(index: $index) {
      hash
    }
    logs(filter: {addresses: [$address], topics: [[$topic]]}) {
      index
      account {
        address
      }
      topics
      data
      transaction {
        hash
      }
    }
    account(address: $address) {
      address
      balance
      transactionCount
      code
      storage(slot: $slot)
    }
    call(data: {from: $sender, to: $address, data: "0x"}) {
      data
      gasUsed
      status
    }
    estimateGas(data: {from: $sender, to: $address, data: "0x"})
    rawHeader
    raw
    withdrawalsRoot
    withdrawals {
      index
      validator
      address
      amount
    }
  }
  blockByHash: block(hash: $hash) {
    number
    hash
  }
  blocks(from: $block, to: $block) {
    number
    hash
  }
  pending {
    transactionCount
    transactions {
      hash
    }
    account(address: $sender) {
      address
      balance
      transactionCount
      code
    }
    call(data: {from: $sender, to: $address, data: "0x"}) {
      data
      gasUsed
      status
    }
    estimateGas(data: {from: $sender, to: $address, data: "0x"})
  }
  transaction(hash: $txHash) {
    hash
    signature
    publicKey
    descriptor
    extraParams
    raw
    rawReceipt
  }
  logs(
    filter: {
      fromBlock: $block
      toBlock: $block
      addresses: [$address]
      topics: [[$topic]]
    }
  ) {
    index
    account {
      address
    }
    topics
    data
    transaction {
      hash
    }
  }
  gasPrice
  maxPriorityFeePerGas
  syncing {
    startingBlock
    currentBlock
    highestBlock
  }
  chainID
}
